"""log_audit nullable user_id and attempted_identifier

Revision ID: 2ca7ad114fe9
Revises: 30d904199c6f
Create Date: 2026-07-08 10:44:05.361703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2ca7ad114fe9'
down_revision: Union[str, Sequence[str], None] = '30d904199c6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log_audit', sa.Column('attempted_identifier', sa.String(length=255), nullable=True))
    op.alter_column('log_audit', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('log_audit', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_column('log_audit', 'attempted_identifier')
    # ### end Alembic commands ###
